version: "3.3"

services:
  mongodb:
    build: ../db
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-spiceComMod}
      - MONGODB_USER=${MONGODB_USER:-spice}
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - TYPE=$TYPE

  app:
    depends_on:
      - mongodb
      - cm
    build: ../apiServer
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_LOG_COLLECTION=log_api
      - DB_USER=${MONGODB_USER:-spice}
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=${MONGODB_DATABASE:-spiceComMod}
      - DB_PORT=27017
      - NODE_DOCKER_PORT=${APP_CONTAINER_PORT:-8080}
      - CM_DOCKER_PORT=${CM_CONTAINER_PORT:-8090}
      - API_USER=${API_USER:-user}
      - API_PASS=${API_PASS:-pass}
      - TYPE=$TYPE
  cm:
    depends_on:
      - mongodb
    image: cm
    build: ../cmServer
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_LOG_COLLECTION=log_cm
      - DB_USER=${MONGODB_USER:-spice}
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=${MONGODB_DATABASE:-spiceComMod}
      - DB_PORT=27017
      - NODE_DOCKER_PORT=${APP_CONTAINER_PORT:-8080}
      - CM_DOCKER_PORT=${CM_CONTAINER_PORT:-8090}
      - API_USER=${API_USER:-user}
      - API_PASS=${API_PASS:-pass}
      - TYPE=$TYPE

